version: '3.8'
services:
  mysqlserver:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=daily_reminder
      - MYSQL_PASSWORD=daily_reminder
      - MYSQL_DATABASE=daily_reminder
    volumes:
      - mysql_data_daily_reminder:/var/lib/mysql
      - mysql_config_daily_reminder:/etc/mysql/conf.d

  daily-reminder:
    build:
      context: .
    ports:
      - "8000:8000"
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver:3306/daily_reminder
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
volumes:
  mysql_data_daily_reminder:
  mysql_config_daily_reminder:
